# Generated by Django 4.0.2 on 2022-03-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='data',
            field=models.FloatField(),
        ),
    ]
